<a href="https://colab.research.google.com/github/JLuisSanchez/Data-Science-AI---Master-Devf/blob/main/Challenge_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###### (2020) Gonzalo G. Peraza Mues

# Ejercicios de NumPy

Ahora que has aprendido acerca de NumPy vamos a poner a prueba tu conocimiento. Comenzaremos con algunas tareas simples y depués se te harán algunas preguntas más complicadas.

IMPORTANTE

Asegurate de no ejecutar las celdas directamente arriba de la salida de ejemplo, ¡de otro modo podrías sobreescribir la salida del ejercicio!

#### 1. Importa NumPy con el nombre np

In [2]:
import numpy as np

#### 2. Crea un arreglo de 10 ceros

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# NO ESCRIBAS AQUI

#### 3. Crea un arreglo de 10 unos

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
# NO ESCRIBAS AQUI

#### 4. Crea un arreglo de 10 cincos

In [7]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
# NO ESCRIBAS AQUI

#### 5. Crea un arreglo de enteros del 10 al 50

In [9]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [10]:
# NO ESCRIBAS AQUI

#### 6. Crea un arreglo con todos los enteros pares del 10 al 50

In [11]:
np.arange(10, 52, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [12]:
# NO ESCRIBAS AQUI

#### 7. Crea una matriz 3x3 con valores del 0 al 8

In [13]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
# NO ESCRIBAS AQUI

#### 8. Crea una matriz identidad 3x3

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# NO ESCRIBAS AQUI

#### 9. Utiliza NumPy para generar un número aleatorio entre 0 y 1. <br><br>&emsp;NOTA: Tu resultado podría ser diferente al valor mostrado abajo.

In [17]:
np.random.randint(0, 1, 1)

array([0])

In [18]:
# NO ESCRIBAS AQUI

#### 10. Utiliza NumPy para generar un arreglo de 25 números aleatorios a partir de una distribución normal estándar.<br><br>&emsp;&ensp;NOTA: Tus resultados podrías ser distintos de los mostrados abajo.

In [19]:
np.random.random(5)

array([0.79737222, 0.83395913, 0.18375082, 0.07819707, 0.43459983])

In [20]:
# NO ESCRIBAS AQUI

#### 11. Crea la siguiente matriz:

In [21]:
np.arange(0.01, 1.01, 0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [22]:
# NO ESCRIBAS AQUI

#### 12. Crea un arreglo de 20 puntos entre 0 y 1 linealmente espaciados:

In [23]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [24]:
# NO ESCRIBAS AQUI

## Selección e indexado con NumPy

Se te dará una matriz inicial (asegurate de ejecutar la celda de abajo), y se te pedira que repliques las matrices resultantes que aparecen abajo:

In [25]:
# EJECUTA ESTA CELDA- ES NUESTRA MATRIZ INICIAL
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Escribe el código que reproduca la salida mostrada abajo. <br><br>&emsp;&ensp; Ten cuidado de no ejecutar la celda inmediantemente arriba de la salida, de otra manera no serás capas de ver la matriz resultado.

In [26]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [27]:
# NO ESCRIBAS AQUI

#### 14. Escribe código que reproduzca la siguiente salida:

In [28]:
mat[3, 4]

20

In [29]:
# NO ESCRIBAS AQUI

#### 15. Escribe código que reproduzca la siguiente salida:

In [30]:
mat[0:3, 1]

array([ 2,  7, 12])

In [31]:
# NO ESCRIBAS AQUI

#### 16. Escribe código que reproduzca la siguiente salida:

In [32]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [33]:
# NO ESCRIBAS AQUI

#### 17. Escribe código que reproduzca la siguiente salida:

In [34]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
# NO ESCRIBAS AQUI

## Operaciones con NumPy

Vamos a resolver algunos ejercicios sencillos con Numpy.

In [36]:
# Definimos un vector
x = np.array([1, 2, 3, 4, 5])
# Y una matriz
m = np.array([[1, 2, 3],[4, 5, 6,], [7, 8, 9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Una operación común que querrá hacer con
vectores o matrices es sumar cada elemento.
La notación puede dar miedo, pero en realidad es
bastante simple:
$$
\sum_{i,j = 1}^n m_{ij}
$$
El símbolo $\Sigma$ es $\sigma$ mayúscula
y se llama "sigma". Significa que para alguna matriz $m$, donde $i$ representa una fila y $j$ representa una columna, sume todos los elementos. $n$ se refiere al número de elementos de la variable $m$.

Aunque puede implementar esta operación usando un bucle for, NumPy lo hace fácil al proporcionar un método `sum`.

Intente implementarlo ahora `m.sum ()`, debes obetener el valor 45.

In [37]:
np.sum(m)

45

Otra operación común es multiplicar cada
valor en un vector o matriz. Esto parece
esto:
$$
\prod_{i,j=1}^n m_{ij}
$$

El símbolo $\Pi$ es un símbolo $\pi$ mayúscula, pronunciado "pi". Implemente esta ecuación de manera similar usando la función `prod`, debe obtener 362880. 

In [38]:
np.prod(m)

362880

#### 18. Obten la suma de todos los valores en mat

In [39]:
np.sum(mat)

325

In [40]:
# NO ESCRIBAS AQUI

¡Perfecto! Ahora, implementemos la desviación estándar:
$$
\sqrt{\frac{1}{n-1}\sum_{i=1}^n (x_i - \bar{x})^2}
$$

Recuerde que $ \bar {x} $ se refiere a la media aritmética de $ x $.
En lugar de implementarlo desde cero, simplemente puede llamar a `x.mean ()`.

#### 19. Obtén la desviación estándar de los valores en mat

In [41]:
np.mean(mat)

13.0

In [42]:
# NO ESCRIBAS AQUI

#### 20. Obtén la suma de todas las columnas en mat

In [43]:
# NO ESCRIBAS AQUI

Hicimos muchos ejercicios con números aleatorios con NumPy, ¿Existe alguna manera en la que podamos obtener siempre la misma salida? [Haz click aqui para una pista](https://www.google.com/search?q=numpy+random+seed&rlz=1C1CHBF_enUS747US747&oq=numpy+random+seed&aqs=chrome..69i57j69i60j0l4.2087j0j7&sourceid=chrome&ie=UTF-8)

In [44]:
# Tu código aquí

¡Estupendo! Ahora está listo para implementar algunos
ecuaciones básicas! Empecemos con la
media aritmética:
$$
\bar{x} = \frac{1}{n}\times \sum_{i=1}^n x_i
$$

Esto simplemente significa agregar cada elemento de un
lista y dividiendo el resultado por el número de
elementos en $ x $. Una barra sobre una variable ($ \bar {x} $) se refiere a un tipo de media.

**Hint:** Puedes obtener la cantidad de elementos
en una matriz en NumPy con `x.size` ..


Comúnmente conocido como: PROMEDIO

#### 21. Calcula la media aritmética de `m` y guardala en la variable 'mean' 

In [45]:
mean = 0

# Tu código aquí

print(f'Calulaste una media de {mean}, debería ser 3.0')

Calulaste una media de 0, debería ser 3.0


¡Buen trabajo! Ahora implementemos algo conocido
como la norma Frobenius (Euclidean norm, norma de un vector, distancia entre dos puntos):
$$
\Vert m \Vert_F = \left(
    \sum_{i,j=1}^n m_{ij}^2
    \right)^{1/2}
$$

**Hint:** Puede implementar esto de varias formas, usando operadores (`**`), funciones (`np.sqrt`) y métodos (` .sum`).

#### 22. Calcula la norma Frobenius para `m`y guardala en la variable f_norm

In [46]:
f_norm = 0

# Tu código aquí

print(f'La norma Frobenius que encontraste es {round(f_norm, 4)}, y esta debe de ser 16.8819')

La norma Frobenius que encontraste es 0, y esta debe de ser 16.8819


#### 23. Como un último reto, vamos a calcular una matriz de distancias en numpy.
Implementa una función que tome como entrada una matrix de datos, donde cada fila es una observación y cada columna una variable, y devuelva otra matriz, la matriz de distancias.

La matriz de distancias es muy utilizado en algoritmos de aprendizaje y tiene la siguiente forma:

$$
D = \begin{pmatrix}
d(x_1,x_1) & d(x_1,x_2) & \dots & d(x_1,x_n)\\
d(x_2,x_1) & d(x_2,x_2) & \dots & d(x_2,x_n)\\
\vdots & \vdots & \ddots & \vdots\\
d(x_n,x_1) & d(x_n,x_2) & \dots & d(x_n,x_n)
\end{pmatrix}
$$

Es una matrix NxN, donde N es el número de observaciones en la matriz de datos. Cada entrada de la matriz $d(x_i,x_j)$ es la distancia entre observación $i$ y $j$, y se calcula como

$$
d(x_i,x_j) = \sqrt{\sum_l (x_{il} - x_{jl})^2}
$$

Es decir, resta cada variable, elemento por elemento, de los vectores de observación, eleva las restas al cuadrado y suma todas. Al final saca la raíz. Esta es la distancia euclidiana o norma-2.

Una de las maneras mas eficientes en computo, aunque no en memoria, es hacer un broadcast en 3D, aunque no es la única manera.

In [47]:
def distance_matrix(X):
    """Retorna la DISTANCIA EUCLIDIANA entre los puntos (datos) de la matriz X. """
    
    # Tu código aquí


    return D

## References
- Adapted from: https://mathtocode.com/ by Vernon Thommeret